# Generated by Django 3.0.7 on 2020-11-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionprice',
            name='available_place_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
