# Generated by Django 3.0.7 on 2020-11-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionprice',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
